Voice-Based-Mail/client/urls.py
from django.urls import re_path,path
from . import views
app_name = 'client'

urlpatterns = [
    re_path(r'^$', views.login, name="login"),
    re_path(r'^options/$', views.options, name="options"),
    re_path(r'^sent/$', views.sent, name="sent"),
    re_path(r'^compose/$', views.compose, name="compose"),
    re_path(r'^inbox/$', views.inbox, name="inbox"),
    re_path(r'^trash/$', views.trash, name="trash"),
    re_path(r'^draft/$', views.draft, name="draft"),
    re_path(r'^register/$', views.register, name = "register")
]

Voice-Based-Mail/vmail/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^', include('client.urls')),
]

urlpatterns += staticfiles_urlpatterns()

Voice-Based-Mail/client/models.py
from django.db import models

class UserRegistration(models.Model):
    email = models.EmailField(unique=True)
    app_password = models.CharField(max_length=100)
    new_password = models.CharField(max_length=100)
    confirm_password = models.CharField(max_length=100)

class UserDetails(models.Model):
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

class DraftEmail(models.Model):
    subject = models.CharField(max_length=255)
    toaddr = models.TextField()
    body = models.TextField()

class option(models.Model):
    option = models.CharField(max_length=100)


class Details:
    email: str
    password: str


class Compose:
    recipient: str
    subject: str
    body: str

Voice-Based-Mail/client/forms.py
from django import forms
from . import models


class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserDetails
        fields = ['email', 'password']
        widgets = {
            'email': forms.EmailInput(),
            'password': forms.PasswordInput(),
        }

Voice-Based-Mail/client/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import forms
from . models import Details
from .models import Compose
from .models import UserRegistration
import imaplib
import sqlite3
import email
from gtts import gTTS
from email.message import EmailMessage
import os
from playsound import playsound
from django.http import HttpResponse
import speech_recognition as sr
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from email.message import EmailMessage
from django.http import JsonResponse
import re
file = "good"
i = "0"
passwrd = ""
addr = ""
item = ""
subject = ""
body = ""
s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()

attachment_dir = 'C:/Users/cricd/Desktop/'
def retrieve_app_password(email, confirm_password):
    # Connect to the SQLite database
    conn = sqlite3.connect('db.sqlite3')
    cursor = conn.cursor()

    # Execute the SQL query to retrieve the app password
    query = "SELECT app_password FROM client_userregistration WHERE email = ? AND confirm_password = ?"
    cursor.execute(query, (email, confirm_password))
    result = cursor.fetchone()

    # Close the database connection
    conn.close()

    if result is not None:
        app_password = result[0]
        return app_password
    else:
        return None

def save_draft_email(request,subject, toaddr, body):
    imap_server = imaplib.IMAP4_SSL('imap.gmail.com')
    print("Inside draft")
    email = request.session.get('email')
    password = request.session.get('password')
    print(email)
    print(passwrd)
    try:
        imap_server.login(email, password)
        imap_server.select("[Gmail]/Drafts")
        message = EmailMessage()
        message['Subject'] = subject
        message['From'] = email
        message['To'] = toaddr
        message.set_content(body)
        imap_server.append("[Gmail]/Drafts", '', None, message.as_bytes())
        print("Email saved as draft in Gmail")
    finally:
        imap_server.logout()

def texttospeech(text, filename):
    filename = filename + '.mp3'
    flag = True
    while flag:
        try:
            tts = gTTS(text=text, lang='en', slow=False)
            tts.save(filename)
            flag = False
        except:
            print('Trying again')
    playsound(filename)
    os.remove(filename)
    return

def speechtotext(duration):
    global i, addr, passwrd
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source, duration=1)
        playsound('speak.mp3')
        audio = r.listen(source, phrase_time_limit=duration)
    try:
        response = r.recognize_google(audio)
    except:
        response = 'N'
    return response

def convert_special_char(text):
    temp = text
    special_chars = ['attherate', 'dot', 'underscore', 'dollar',
                     'hash', 'star', 'plus', 'minus', 'space', 'dash']
    for character in special_chars:
        while (True):
            pos = temp.find(character)
            if pos == -1:
                break
            else:
                if character == 'attherate':
                    temp = temp.replace('attherate', '@')
                elif character == 'dot':
                    temp = temp.replace('dot', '.')
                elif character == 'underscore':
                    temp = temp.replace('underscore', '_')
                elif character == 'dollar':
                    temp = temp.replace('dollar', '$')
                elif character == 'hash':
                    temp = temp.replace('hash', '#')
                elif character == 'star':
                    temp = temp.replace('star', '*')
                elif character == 'plus':
                    temp = temp.replace('plus', '+')
                elif character == 'minus':
                    temp = temp.replace('minus', '-')
                elif character == 'space':
                    temp = temp.replace('space', '')
                elif character == 'dash':
                    temp = temp.replace('dash', '-')
    return temp

def register(request):
    if request.method == 'POST':
        email = request.POST['email']
        print(email)
        app_password = request.POST['app_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        # Check if the new password matches the confirm password
        if new_password != confirm_password:
            return render(request, 'register.html', {'error': 'Passwords do not match'})

        # Create a new user object
        user = UserRegistration(email=email, app_password=app_password,new_password=new_password,confirm_password=confirm_password)

        user.save()

        # Redirect to a success page or login page
        return render(request, 'client/login.html')

    return render(request, 'client/register.html')

def login(request):
    global i, addr, passwrd
    if request.method == 'POST':
        wel = "Welcome to our Virtually Assisted Email System.If you are a first time user please register with the help of an assistant . Login with your email. "
        texttospeech(wel, file+i)
        flag = True
        while (flag):
            texttospeech("Enter your Email address", file + i)
            i = i + str(1)
            addr = speechtotext(5)

            if addr != 'N':
                texttospeech("You meant " + addr +
                             " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                print(say)
                if say == "yes" or say == "Yes":
                    flag = False
                else:
                    flag = True
            else:
                texttospeech("Please interact again", file + i)
                i = i + str(1)
            print(flag)
        addr = addr.strip()
        addr = addr.replace(' ', '')
        addr = addr.lower()
        addr = convert_special_char(addr)
        
        # addr = "rapid3054@gmail.com"
        # print(addr)
        request.email = addr
        request.session['email'] = addr
        flag = True
        while (flag):
            texttospeech("Enter your password", file + i)
            i = i + str(1)
            passwrd = speechtotext(5)

            if addr != 'N':
                texttospeech("You meant " + passwrd +
                             " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                print(say)
                if say == "yes" or say == "Yes":
                    flag = False
                else:
                    flag = True
            else:
                texttospeech("Please interact again", file + i)
                i = i + str(1)
            print(flag)
        passwrd = passwrd.strip()
        passwrd = passwrd.replace(' ', '')
        passwrd = passwrd.lower()
        # passwrd = 'pass'
        passwrd = convert_special_char(passwrd)
        app_pwd = retrieve_app_password(addr,passwrd)
        if(app_pwd==None):
            texttospeech("Invalid Login Details. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})
        else:
            passwrd = app_pwd
        print(passwrd)
        request.session['password']= passwrd
        imap_url = 'imap.gmail.com'
        conn = imaplib.IMAP4_SSL(imap_url, 993)
        try:
            conn.login(addr, passwrd)
            s.login(addr, passwrd)
            texttospeech(
                "Congratulations. You have logged in . We will redirect you to our main page", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'success'})
        except:
            texttospeech("Invalid Login Details. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})
    detail = Details()
    detail.email = addr
    detail.password = passwrd
    return render(request, 'client/login.html')

def options(request):
    global i, addr, passwrd
    if request.method == 'POST':
        flag = True
        texttospeech(
            "You are logged into your account. What would you like to do ?", file + i)
        i = i + str(1)
        while (flag):
            texttospeech("To compose an email say compose. To open Inbox folder say Inbox. To open Sent folder say Sent. To open Trash folder say Trash. To Logout say out. Do you want me to repeat?", file + i)
            i = i + str(1)
            say = speechtotext(3)
            if say == 'No' or say == 'no':
                flag = False
        texttospeech("Enter your desired action", file + i)
        i = i + str(1)
        act = speechtotext(5)
        print(act)
        act = act.lower()
        if act == 'compose':
            return JsonResponse({'result': 'compose'})
        elif act == 'inbox':
            return JsonResponse({'result': 'inbox'})
        elif act == 'sent':
            return JsonResponse({'result': 'sent'})
        elif act == 'trash':
            return JsonResponse({'result': 'trash'})
        elif act == 'save':
            return JsonResponse({'result': 'draft'})
        elif act == 'out':
            addr = ""
            passwrd = ""
            texttospeech(
                "You have been logged out of your account and now will be redirected back to the login page.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'logout'})
        
        else:

Voice-Based-Mail/client/templates/client/draft.html
{% extends 'base_layout.html' %}

{% block content %}
<style>
    a,input,button{
      pointer-events: none;
      cursor: not-allowed;
    }
  </style>
<style>
    .container {
        background-color: aqua;
        max-width: 100%;
    }

    .card {
        background-color: darkblue;
    }

    a {
        margin-bottom: 7px;
    }
</style>

<body onmousedown="enablePostDraft(event)">

    <div class="container">
        <div class="row align-items-center vh-100">
            <div class="col-6 mx-auto">
                <div class="card shadow border" style="width:auto; height: auto;">
                    <div class="card-body d-flex flex-column align-items-center">
                        <p style="color:white;font-size: 25px;">Draft Page</p>
                        <a href="options.html">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                            <input role="button" href="options.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Back" type="submit">
                        </a>
                        <a href="inbox.html">
                            <i class="fa fa-inbox" aria-hidden="true"></i>
                            <input role="button" href="inbox.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Search" type="submit">
                        </a>
                        <a href="login.html">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            <input role="button" href="logout.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Logout" type="submit">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function enablePostDraft(event) {
            $.ajax({
                url: "{% url 'client:draft' %}",
                method: 'POST',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    if (data.result == 'success') {
                        window.location = "{% url 'client:options' %}";
                    } else if (data.result == 'logout') {
                        window.location = "{% url 'client:login' %}";
                    }
                }
            });
        }
    </script>
</body>

{% endblock %}

Voice-Based-Mail/client/templates/client/inbox.html
{% extends 'base_layout.html' %}
{% block content %}
<style>
    a,input,button{
      pointer-events: none;
      cursor: not-allowed;
    }
  </style>
<style>
    .container{
        background-color: aqua;
        max-width: 100%;
    }
    .card{
        background-color: darkblue;
    }
    a{

        margin-bottom: 7px;
    }
</style>

    <body onmousedown="enableOptionInbox(event)">
        <div class="container">
            <div class="row align-items-center vh-100">
                <div class="col-6 mx-auto">
                    <div class="card shadow border" style="width:auto; height: auto;">
                        <div class="card-body d-flex flex-column align-items-center">
                            <p style="color:white;font-size: 25px;"> Inbox Page</p>
                            <a href="compose.html">
                                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                <input role="button" href="compose.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Unread" type="submit">  
                            </a>
                            <a href="inbox.html">
                                <i class="fa fa-inbox" aria-hidden="true"></i>
                                <input role="button" href="inbox.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Search" type="submit">                           
                            </a>
                            <a href="options.html">
                                <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                                <input role="button" href="options.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Back" type="submit">   
                            </a>
                            <a href="login.html">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                <input role="button" href="logout.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Logout" type="submit">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            function enableOptionInbox(event){
                $.ajax({
                url: "{% url 'client:inbox' %}",
                method: 'POST',
                data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data) {
                    if(data.result == 'success'){
                        window.location = "{% url 'client:options' %}";
                    }
                    else if(data.result == 'logout'){
                        window.location = "{% url 'client:login' %}";
                    }
                }
            });
            }
            </script>
    </body>
{% endblock %}

Voice-Based-Mail/client/templates/client/options.html
{% extends 'base_layout.html' %}
{% block content %}
<style>
  a,input,button{
    pointer-events: none;
    cursor: not-allowed;
  }

    .container {
        background-color: aqua;
        max-width: 100%;
    }

    .card {
        background-color: darkblue;
    }

    a {

        margin-bottom: 7px;
    }
</style>

<body onmousedown="enablePostOptions(event)">

    <div class="container">
        <div class="row align-items-center vh-100">
            <div class="col-6 mx-auto">
                <div class="card shadow border" style="width:auto; height: auto;">
                    <div class="card-body d-flex flex-column align-items-center">
                        <p style="color:white;font-size: 25px;"> Menu Page</p>
                        <a href="compose.html">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            <input role="button" href="compose.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Compose" type="submit">
                        </a>
                        <a href="inbox.html">
                            <i class="fa fa-inbox" aria-hidden="true"></i>
                            <input role="button" href="inbox.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Inbox" type="submit">
                        </a>
                        <a href="draft.html">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                            <input role="button" href="draft.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Draft" type="submit">
                        </a>
                        <a href="sent.html">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                            <input role="button" href="sent.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Sent" type="submit">
                        </a>
                        <a href="trash.html">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                            <input role="button" href="trash.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Trash" type="submit">
                        </a>
                        <a href="login.html">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            <input role="button" href="logout.html" class="btn btn-primary"
                                style="font-size: 25px;margin-bottom: 6px;" value="Logout" type="submit">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function enablePostOptions(event) {
            $.ajax({
                url: "{% url 'client:options' %}",
                method: 'POST',
                data: { 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                success: function (data) {
                    if (data.result == 'compose') {
                        window.location = "{% url 'client:compose' %}";
                    }
                    else if (data.result == 'sent') {
                        window.location = "{% url 'client:sent' %}";
                    }
                    else if (data.result == 'inbox') {
                        window.location = "{% url 'client:inbox' %}";
                    }
                    else if (data.result == 'draft') {
                        window.location = "{% url 'client:draft' %}"
                    }
                    else if (data.result == 'trash') {
                        window.location = "{% url 'client:trash' %}";
                    }
                    else if (data.result == 'logout') {
                        window.location = "{% url 'client:login' %}";
                    }
                    else if (data.result == 'failure') {
                        window.location = "{% url 'client:options' %}";
                    }
                }
            });
        }
    </script>
</body>

{% endblock %}

Voice-Based-Mail/client/templates/client/register.html
{% extends 'base_layout.html' %}
{% block content %}

<body onmousedown="enablePostRequest(event)">
  <section class="vh-150" style="background-color: aqua;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">

              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">

                  <form action="{% url 'client:register' %}" method="post">

                    <div class="d-flex align-items-center mb-3 pb-1">
                      <span class="h1 fw-bold mb-0">Voice based Email</span>
                    </div>

                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Register your account</h5>
                    <div id="here">
                      <script>
                        $(document).ready(function () {
                          setInterval(function () {
                            $("#here").load(window.location.href + " #here");
                          }, 1000);
                        });
                      </script>
                      {% csrf_token %}
                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example17">Email</label>
                        <input type="email" id="form2Example17" class="form-control form-control-lg" placeholder="Email"
                          name="email" required value="{{ detail.email }}" />
                      </div>
                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example27">App Password</label>
                        <input type="password" id="form2Example27" class="form-control form-control-lg"
                          placeholder="App Password" name="app_password" required value="{{ detail.app_password }}" />
                      </div>
                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example28">New Password</label>
                        <input type="password" id="form2Example28" class="form-control form-control-lg"
                          placeholder="New Password" name="new_password" required value="{{ detail.new_password }}" />

                      </div>

                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example29">Confirm Password</label>
                        <input type="password" id="form2Example29" class="form-control form-control-lg"
                          placeholder="Confirm Password" name="confirm_password" required
                          value="{{ detail.confirm_password }}" />

                      </div>

                      <input type="submit" class="btn btn-primary btn-xl rounded-pill mt-5" role="button"
                        value="REGISTER" style="background-color: black;">
                      <a href="{% url 'client:login' %}" class="btn btn-primary btn-xl rounded-pill mt-5" role="button"
                        style="background-color: black;">Back to Login</a>
                      <br><br>
                      <p>For the first time, please ask an assistant to help set up your account by going to /register
                        in the URL and entering your email and app password.</p>
                      <br>
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script>

    function enablePostRequest(event) {

      $.ajax({
        url: "{% url 'client:register' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}' },
        success: function (data) {

          if (data.result == 'success') {

            window.location = "{% url 'client:options' %}";
          }
          else if (data.result == 'failure') {
            window.location = "{% url 'client:register' %}";
          }
        }
      });
    }
  </script>

  {% endblock %}

Voice-Based-Mail/client/templates/client/sent.html
{% extends 'base_layout.html' %}
{% block content %}
<style>

  a,input,button{
    pointer-events: none;
    
    cursor: not-allowed;
  }

    .container{
        background-color: aqua;
        max-width: 100%;
    }
    .card{
        background-color: darkblue;
    }
    a{
        margin-bottom: 7px;
    }
</style>
<body onmousedown="enablePostSent(event)">
   
    <div class="container">
        <div class="row align-items-center vh-100">
            <div class="col-6 mx-auto">
                <div class="card shadow border" style="width:auto; height: auto;">
                    <div class="card-body d-flex flex-column align-items-center">
                        <p style="color:white;font-size: 25px;"> Sent Mail Page</p>
                        <a href="options.html">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                            <input role="button" href="options.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Back" type="submit">  
                        </a>
                        <a href="inbox.html">
                            <i class="fa fa-inbox" aria-hidden="true"></i>
                            <input role="button" href="inbox.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Search" type="submit">                           
                        </a>
                        <a href="login.html">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            <input role="button" href="logout.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Logout" type="submit">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function enablePostSent(event){
            $.ajax({
        url: "{% url 'client:sent' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'client:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'client:login' %}";
			}
        }
    });
        }
        </script>
</body>
{% endblock %}

Voice-Based-Mail/client/templates/client/trash.html
{% extends 'base_layout.html' %}
{% block content %}
<style>
    a,input,button{
      pointer-events: none;
      
      cursor: not-allowed;
    }
  </style>
<style>
    .container{
        background-color: aqua;
        max-width: 100%;
    }
    .card{
        background-color: darkblue;
    }
    a{

        margin-bottom: 7px;
    }
</style>
<body onmousedown="enablePostTrash(event)">
   
    <div class="container">
        <div class="row align-items-center vh-100">
            <div class="col-6 mx-auto">
                <div class="card shadow border" style="width:auto; height: auto;">
                    <div class="card-body d-flex flex-column align-items-center">
                        <p style="color:white;font-size: 25px;"> Trash Page</p>
                        <a href="options.html">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                            <input role="button" href="options.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Back" type="submit">  
                        </a>
                        <a href="inbox.html">
                            <i class="fa fa-inbox" aria-hidden="true"></i>
                            <input role="button" href="inbox.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Search" type="submit">                           
                        </a>
                        <a href="login.html">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            <input role="button" href="logout.html" class="btn btn-primary" style="font-size: 25px;margin-bottom: 6px;" value="Logout" type="submit">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function enablePostTrash(event){
            $.ajax({
        url: "{% url 'client:trash' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'client:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'client:login' %}";
			}
        }
    });
        }
        </script>
</body>
{% endblock %}